[package]
name = "MachineLearningGPU"
version = "0.1.0"
edition = "2024"

[dependencies]
async-std = "1.13.1"
bytemuck = "1.23.2"
csv = "1.3.1"
itertools = "0.14.0"
pollster = "0.4.0"
rand = "0.9.2"
wgpu = "26.0.1"
